name: song_indexer
description: A sample command      -line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.17.5 <3.0.0"

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
dependencies:
  { flutter: { sdk: flutter }, ftpconnect: ^1.0.1, html: ^0.15.0, path_provider: ^2.0.11, webview_flutter: ^3.0.4 }

flutter:
  uses-material-design: true
  assets:
  - index/songs.json


   
