name: song_indexer
description: A sample command      -line application.
version: 1.0.5+6
# homepage: https://www.example.com

environment:
  sdk: ">=2.17.5 <3.0.0"

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
dependencies:
  { flutter: { sdk: flutter }, flutter_launcher_icons: ^0.10.0, html: ^0.15.0, path_provider: ^2.0.11, shared_preferences: ^2.0.15}

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "icon.png"

flutter:
  uses-material-design: true
  assets:
  - index/songs.json


   
